# DO NOT EDIT THIS FILE!
#
# Python module ASTER_ORB generated by omniidl

import omniORB
omniORB.updateModule("ASTER_ORB")

# ** 1. Stub files contributing to this module
import ASTER_Gen_idl

# ** 2. Sub-modules

# ** 3. End
